#!/usr/bin/env bash

#this creates a set of tests, that ensures, that all itnernal headers can be build independently

set -e

internal_headers=$(find ../../include -path "*cuda/std/__*/*" -not -path "*/__cuda/*")

cd ../../test/libcxx/selftest/internal_headers

for f in $internal_headers
do
    short_path=${f##*../include/}
    test_name=${f##*include/}
    test_name=${test_name%.h}.pass.cpp

    mkdir -p -- "${test_name%/*}"
    cat > $test_name << EOL
//===----------------------------------------------------------------------===//
//
// Part of libcu++, the C++ Standard Library for your entire system,
// under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
// SPDX-FileCopyrightText: Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES.
//
//===----------------------------------------------------------------------===//

#include <cuda/std/version>
#include <$short_path>

int main(int, char**) { return 0; }
EOL
done
