#!/usr/bin/env bash

set -euo pipefail

root_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)

stdlib_headers=$(<"${root_dir}/maintenance/stdlib-headers")
# shellcheck disable=SC2001
header_replacements=$(echo "${stdlib_headers}" | sed 's#<\(.*\)>#-e s:<cuda/std/\1>:<\1>:g#')

find "${root_dir}/test" -name "*.cpp" |
while read -r file
do
    sed -i "${file}" "${header_replacements}"
    sed -i "${file}" -e 's/cuda::std::/std::/g'
done
