changelog:
  categories:
    - title: 🚀 Thrust / CUB
      labels:
        - "thrust"
        - "cub"
    - title: 📚 Libcudacxx
      labels:
        - "libcu++"
    - title: 🤝 cuda.coop.numba_cuda
      labels:
        - "cuda.coop"
    - title: ⚡ cuda.compute
      labels:
        - "cuda.compute"
    - title: 📝 Documentation
      labels:
        - "doc"
    - title: 🔄 Other Changes
      labels:
        - "*"
