changelog:
  categories:
    - title: 💻 C++ - 🚀 Thrust / CUB
      labels:
        - "thrust"
        - "cub"
    - title: 💻 C++ - 📚 Libcudacxx
      labels:
        - "libcu++"
    - title: 🐍 Python - 🤝 cuda.cooperative
      labels:
        - "cuda.cooperative"
    - title: 🐍 Python - ⚡ cuda.parallel
      labels:
        - "cuda.parallel"
    - title: 📝 Documentation
      labels:
        - "doc"
    - title: 🔄 Other Changes
      labels:
        - "*"
