changelog:
  categories:
    - title: 🚀 Thrust / CUB
      labels:
        - "thrust"
        - "cub"
    - title: 📚 Libcudacxx
      labels:
        - "libcu++"
    - title: 🤝 cuda.cooperative
      labels:
        - "cuda.cooperative"
    - title: ⚡ cuda.parallel
      labels:
        - "cuda.parallel"
    - title: 📝 Documentation
      labels:
        - "doc"
    - title: 🔄 Other Changes
      labels:
        - "*"
