# Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. ALL RIGHTS RESERVED.
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

"""Wheel-content contracts for the cuda-coop distribution."""

import importlib.metadata
import importlib.util
import json
from pathlib import Path

import pytest

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover - exercised on Python 3.10
    import tomli as tomllib

from ...support.paths import PACKAGE_ROOT

_EXPECTED_PACKAGE_MAP = {"cuda/coop": "cuda/coop"}
_TYPING_ARTIFACTS = (
    "cuda/coop/py.typed",
    "cuda/coop/__init__.pyi",
    "cuda/coop/_typing.pyi",
    "cuda/coop/cutlass/py.typed",
    "cuda/coop/cutlass/__init__.pyi",
    "cuda/coop/cutlass/_group_adjacent_difference.pyi",
    "cuda/coop/cutlass/_group_discontinuity.pyi",
    "cuda/coop/cutlass/_group_exchange.pyi",
    "cuda/coop/cutlass/_group_histogram.pyi",
    "cuda/coop/cutlass/_group_load_store.pyi",
    "cuda/coop/cutlass/_group_merge_sort.pyi",
    "cuda/coop/cutlass/_group_radix.pyi",
    "cuda/coop/cutlass/_group_reduce.pyi",
    "cuda/coop/cutlass/_group_run_length_decode.pyi",
    "cuda/coop/cutlass/_group_scan.pyi",
    "cuda/coop/cutlass/_group_shuffle.pyi",
    "cuda/coop/cutlass/_group_topk.pyi",
    "cuda/coop/cutlass/_types.pyi",
    "cuda/coop/cutlass/aot.pyi",
    "cuda/coop/cutlass/_block/__init__.pyi",
    "cuda/coop/cutlass/_warp/__init__.pyi",
    "cuda/coop/numba_mlir/py.typed",
    "cuda/coop/numba_mlir/__init__.pyi",
    "cuda/coop/numba_mlir/_block/__init__.pyi",
    "cuda/coop/numba_mlir/_warp/__init__.pyi",
)

_RETIRED_PUBLIC_SCOPE_PREFIXES = (
    "cuda/coop/cutlass/block/",
    "cuda/coop/cutlass/warp/",
    "cuda/coop/numba_mlir/block/",
    "cuda/coop/numba_mlir/warp/",
)


def _scikit_build_wheel_config() -> dict:
    with (PACKAGE_ROOT / "pyproject.toml").open("rb") as stream:
        return tomllib.load(stream)["tool"]["scikit-build"]["wheel"]


def _project_dependencies() -> list[str]:
    with (PACKAGE_ROOT / "pyproject.toml").open("rb") as stream:
        return tomllib.load(stream)["project"]["dependencies"]


def _project_optional_dependencies() -> dict[str, list[str]]:
    with (PACKAGE_ROOT / "pyproject.toml").open("rb") as stream:
        return tomllib.load(stream)["project"]["optional-dependencies"]


def _installed_wheel_files() -> tuple[str, ...]:
    try:
        distribution = importlib.metadata.distribution("cuda-coop")
    except importlib.metadata.PackageNotFoundError:
        pytest.skip("cuda-coop is not installed; wheel checks need the built wheel")
    direct_url = distribution.read_text("direct_url.json")
    if direct_url is not None and json.loads(direct_url).get("dir_info", {}).get(
        "editable", False
    ):
        pytest.skip("cuda-coop is editable; wheel checks need the built wheel")
    spec = importlib.util.find_spec("cuda.coop._core")
    imported = Path(spec.origin).resolve()
    installed = Path(
        str(distribution.locate_file("cuda/coop/_core/__init__.py"))
    ).resolve()
    if imported != installed:
        pytest.skip("cuda.coop does not import from the installed cuda-coop wheel")
    # Exclude installer-generated bytecode; callers scope distribution metadata
    # to the package subtree they are auditing.
    return tuple(
        file.as_posix()
        for file in distribution.files or ()
        if "__pycache__" not in file.parts and file.suffix != ".pyc"
    )


def test_wheel_package_map_owns_the_complete_cuda_coop_root():
    assert _scikit_build_wheel_config()["packages"] == _EXPECTED_PACKAGE_MAP


def test_typing_extensions_is_a_direct_runtime_dependency():
    assert "typing_extensions>=4.12.0" in _project_dependencies()


def test_cuda_pathfinder_is_a_direct_runtime_dependency():
    assert "cuda-pathfinder>=1.2.3" in _project_dependencies()


def test_backend_extras_are_dependency_only_and_use_public_names():
    extras = _project_optional_dependencies()

    assert {"cu12", "cu13"} <= set(extras)
    assert extras["cu13"] == [
        "cuda-bindings>=13.0.0,<14.0.0",
        "cuda-toolkit[nvrtc,nvjitlink,cudart,nvcc,nvvm]==13.*",
    ]
    assert extras["cutlass"] == [
        "cuda-coop[cu13]",
        "nvidia-cutlass-dsl>=4.8,<5",
    ]
    assert extras["cutlass-cu12"] == [
        "cuda-coop[cu12]",
        "nvidia-cutlass-dsl>=4.8,<5",
    ]
    assert extras["cutlass-cu13"] == extras["cutlass"]
    assert extras["numba-cuda-mlir"] == [
        "cuda-coop[cu13]",
        "numba-cuda-mlir[cu13]>=0.5.0",
    ]
    assert extras["numba-cuda-mlir-cu12"] == [
        "cuda-coop[cu12]",
        "numba-cuda-mlir[cu12]>=0.5.0",
    ]
    assert extras["numba-cuda-mlir-cu13"] == [
        "cuda-coop[cu13]",
        "numba-cuda-mlir[cu13]>=0.5.0",
    ]


def test_base_dependencies_do_not_select_a_dsl_runtime():
    assert _project_dependencies() == [
        "cuda-core",
        "cuda-pathfinder>=1.2.3",
        "numpy",
        "typing_extensions>=4.12.0",
    ]


def test_wheel_metadata_is_reproducible_and_python_minor_independent():
    wheel = _scikit_build_wheel_config()

    assert wheel["py-api"] == "py3"
    assert wheel["reproducible"] is True
    assert wheel["license-files"] == []
    assert wheel["force-include"] == {
        "../../LICENSE": "${SKBUILD_METADATA_DIR}/licenses/LICENSE",
        "../../cub/LICENSE.TXT": "${SKBUILD_METADATA_DIR}/licenses/cub/LICENSE.TXT",
        "../../cudax/LICENSE.TXT": "${SKBUILD_METADATA_DIR}/licenses/cudax/LICENSE.TXT",
        "../../libcudacxx/LICENSE.TXT": (
            "${SKBUILD_METADATA_DIR}/licenses/libcudacxx/LICENSE.TXT"
        ),
        "../../thrust/LICENSE": "${SKBUILD_METADATA_DIR}/licenses/thrust/LICENSE",
    }


def test_installed_wheel_ships_supported_python_payloads():
    installed = set(_installed_wheel_files())

    assert {
        "cuda/coop/__init__.py",
        "cuda/coop/_core/__init__.py",
        "cuda/coop/_core/_auto_registration.py",
        "cuda/coop/_headers/__init__.py",
        "cuda/coop/cutlass/__init__.py",
        "cuda/coop/numba_mlir/__init__.py",
    } <= installed


def test_installed_wheel_ships_public_typing_artifacts():
    installed = set(_installed_wheel_files())

    assert set(_TYPING_ARTIFACTS) <= installed


def test_installed_wheel_uses_only_private_qualified_scope_packages():
    installed = set(_installed_wheel_files())

    assert {
        "cuda/coop/cutlass/_block/__init__.py",
        "cuda/coop/cutlass/_warp/__init__.py",
        "cuda/coop/numba_mlir/_block/__init__.py",
        "cuda/coop/numba_mlir/_warp/__init__.py",
    } <= installed
    assert not any(
        path.startswith(prefix)
        for path in installed
        for prefix in _RETIRED_PUBLIC_SCOPE_PREFIXES
    )


def test_installed_pep561_markers_are_empty():
    _installed_wheel_files()
    distribution = importlib.metadata.distribution("cuda-coop")

    for marker in (
        artifact for artifact in _TYPING_ARTIFACTS if artifact.endswith("py.typed")
    ):
        path = Path(str(distribution.locate_file(marker)))
        assert path.read_bytes() == b""


def test_installed_wheel_ships_private_cccl_headers():
    installed = set(_installed_wheel_files())

    assert {
        "cuda/coop/_headers/include/cub/block/block_reduce.cuh",
        "cuda/coop/_headers/include/cuda/experimental/coop.cuh",
    } <= installed


def test_installed_wheel_ships_component_licenses():
    licenses = {
        path for path in _installed_wheel_files() if ".dist-info/licenses/" in path
    }

    assert {path.rsplit("/licenses/", 1)[1] for path in licenses} == {
        "LICENSE",
        "cub/LICENSE.TXT",
        "cudax/LICENSE.TXT",
        "libcudacxx/LICENSE.TXT",
        "thrust/LICENSE",
    }
