# Copyright (c) 2024, NVIDIA CORPORATION.

[tool.ruff]
target-version = "py310"

[tool.codespell]
# To run codespell interactively and fix errors that pre-commit reports, try
# `codespell -i 3 -w -H`. This will run with interactive review (-i 3), writes
# changes to disk (-w), and includes hidden files (-H).
# Note: pre-commit passes explicit lists of files here, which this skip file
# list doesn't override - the skip list is only to allow you to run codespell
# interactively.
skip = "./.git,./build,./CITATION.md"
# ignore short words, and typename parameters like OffsetT
ignore-regex = "\\b(.{1,4}|[A-Z]\\w*T)\\b"
ignore-words-list = "inout,imovable,optionN,aCount,quitted,Invokable,countr,unexpect,numer,euclidian,couldn,OffsetT"
builtin = "clear"
quiet-level = 3
