// This file is autogenerated by configuring stf_header_unittest.in.cu.

// clang-format off
#define UNITTESTED_FILE "@source@"

#include <cuda/experimental/__stf/utility/unittest.cuh>

#include <@source@>
//clang-format on
