set(CUDA_NEXT_VERSION_MAJOR 0)
set(CUDA_NEXT_VERSION_MINOR 1)
set(CUDA_NEXT_VERSION_PATCH 0)
set(CUDA_NEXT_VERSION_TWEAK 0)

set(CUDA_NEXT_VERSION "${CUDA_NEXT_VERSION_MAJOR}.${CUDA_NEXT_VERSION_MINOR}.${CUDA_NEXT_VERSION_PATCH}.${CUDA_NEXT_VERSION_TWEAK}")

set(PACKAGE_VERSION ${CUDA_NEXT_VERSION})
set(PACKAGE_VERSION_COMPATIBLE FALSE)
set(PACKAGE_VERSION_EXACT FALSE)
set(PACKAGE_VERSION_UNSUITABLE FALSE)

# Semantic versioning:
if(PACKAGE_VERSION VERSION_GREATER_EQUAL PACKAGE_FIND_VERSION)
  if(CUDA_NEXT_VERSION_MAJOR VERSION_EQUAL PACKAGE_FIND_VERSION_MAJOR)
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
  endif()

  if(PACKAGE_FIND_VERSION VERSION_EQUAL PACKAGE_VERSION)
    set(PACKAGE_VERSION_EXACT TRUE)
  endif()
endif()
