# TODO we should parse this from a header, and update to CalVer if that's still POR
set(CCCL_VERSION_MAJOR 2)
set(CCCL_VERSION_MINOR 1)
set(CCCL_VERSION_PATCH 0)
set(CCCL_VERSION_TWEAK 0)

set(CCCL_VERSION "${CCCL_VERSION_MAJOR}.${CCCL_VERSION_MINOR}.${CCCL_VERSION_PATCH}.${CCCL_VERSION_TWEAK}")

# TODO decide and implement versioning logic.
set(PACKAGE_VERSION ${CCCL_VERSION})
set(PACKAGE_VERSION_COMPATIBLE TRUE)
set(PACKAGE_VERSION_EXACT TRUE)
set(PACKAGE_VERSION_UNSUITABLE FALSE)
