name: "CCCL Docs Build"
description: "Builds the CCCL documentation to a specified directory."

inputs:
  target_dir:
    description: "Directory to build documentation into"
    required: true


runs:
  using: "composite"
  steps:
    # Install required dependencies
    - name: Install docs build dependencies
      shell: bash --noprofile --norc -euo pipefail {0}
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build python3-venv git flex bison

    # Build all docs
    - name: Build all docs
      shell: bash --noprofile --norc -euo pipefail {0}
      run: ./docs/gen_docs.bash

    # Copy all docs to target directory
    - name: Copy docs to target directory
      shell: bash --noprofile --norc -euo pipefail {0}
      run: |
        mkdir -p "${{ inputs.target_dir }}"
        cp -rf ./docs/_build/html/* "${{ inputs.target_dir }}/"
        touch "${{ inputs.target_dir }}/.nojekyll"
        ./docs/scrape_docs.bash "${{ inputs.target_dir }}"
