#! /bin/bash

HOST_ARCH=x86_64
HOST_OS_KIND=ubuntu
HOST_OS_VERSION=21.10
TARGET_ARCH=x86_64
TARGET_OS_KIND=ubuntu
TARGET_OS_VERSION=21.10
COMPILER_KIND=clang
COMPILER_VERSION=13
COMPILER_CXX_DIALECT=14

