# Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. ALL RIGHTS RESERVED.
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

"""Block-scoped cooperative primitive semantic builders."""

from .._bindings import ArgumentBinding, BindingKind, binding
from ._common import (
    BlockTileBoundary,
    normalize_block_dim,
    normalize_boolean_option,
    normalize_positive_int,
)
from .adjacent_difference import (
    BlockAdjacentDifferenceBoundary,
    BlockAdjacentDifferenceDirection,
    BlockAdjacentDifferenceSemantics,
    BlockAdjacentDifferenceSpec,
    BlockAdjacentDifferenceTilePolicy,
    make_block_adjacent_difference_semantics,
    make_block_adjacent_difference_spec,
)
from .discontinuity import (
    BlockDiscontinuityMode,
    BlockDiscontinuitySemantics,
    BlockDiscontinuitySpec,
    make_block_discontinuity_semantics,
    make_block_discontinuity_spec,
)
from .exchange import (
    BlockExchangeMode,
    BlockExchangeSemantics,
    BlockExchangeSpec,
    BlockExchangeValueForm,
    make_block_exchange_semantics,
    make_block_exchange_spec,
)
from .histogram import (
    BlockHistogramAlgorithm,
    BlockHistogramOperation,
    BlockHistogramSemantics,
    BlockHistogramSpec,
    make_block_histogram_semantics,
    make_block_histogram_spec,
    normalize_block_histogram_algorithm,
    normalize_block_histogram_positive_int,
    validate_block_histogram_output_capacity,
)
from .load_store import (
    BlockLoadAlgorithm,
    BlockLoadStoreAlgorithm,
    BlockLoadStoreKind,
    BlockLoadStoreSemantics,
    BlockLoadStoreSpec,
    BlockStoreAlgorithm,
    make_block_load_spec,
    make_block_load_store_semantics,
    make_block_load_store_spec,
    make_block_store_spec,
)
from .reduce import (
    BlockReduceAlgorithm,
    BlockReduceOperation,
    BlockReduceSemantics,
    BlockReduceSpec,
    BlockReduceValueKind,
    make_block_reduce_semantics,
    make_block_reduce_spec,
    normalize_block_reduce_algorithm,
)
from .run_length import (
    BLOCK_RUN_LENGTH_DECODE_DRIVER,
    BlockRunLengthDecodeOutput,
    BlockRunLengthDecodeSemantics,
    BlockRunLengthDecodeSpec,
    BlockRunLengthDecodeStage,
    BlockRunLengthDecodeWindow,
    make_block_run_length_decode_semantics,
    make_block_run_length_decode_spec,
)
from .scan import (
    BlockScanAlgorithm,
    BlockScanSpec,
    ScanMode,
    ScanSemantics,
    ScanValueKind,
    make_block_scan_spec,
    make_scan_semantics,
    normalize_block_scan_algorithm,
)
from .shuffle import (
    BlockShuffleMode,
    BlockShuffleSemantics,
    BlockShuffleSpec,
    BlockShuffleValueKind,
    make_block_shuffle_semantics,
    make_block_shuffle_spec,
)

__all__ = [
    "BLOCK_RUN_LENGTH_DECODE_DRIVER",
    "ArgumentBinding",
    "BindingKind",
    "BlockAdjacentDifferenceBoundary",
    "BlockAdjacentDifferenceDirection",
    "BlockAdjacentDifferenceSemantics",
    "BlockAdjacentDifferenceSpec",
    "BlockAdjacentDifferenceTilePolicy",
    "BlockDiscontinuityMode",
    "BlockDiscontinuitySemantics",
    "BlockDiscontinuitySpec",
    "BlockExchangeMode",
    "BlockExchangeSemantics",
    "BlockExchangeSpec",
    "BlockExchangeValueForm",
    "BlockHistogramAlgorithm",
    "BlockHistogramOperation",
    "BlockHistogramSemantics",
    "BlockHistogramSpec",
    "BlockLoadAlgorithm",
    "BlockLoadStoreAlgorithm",
    "BlockLoadStoreKind",
    "BlockLoadStoreSemantics",
    "BlockLoadStoreSpec",
    "BlockReduceAlgorithm",
    "BlockReduceOperation",
    "BlockReduceSemantics",
    "BlockReduceSpec",
    "BlockReduceValueKind",
    "BlockRunLengthDecodeOutput",
    "BlockRunLengthDecodeSemantics",
    "BlockRunLengthDecodeSpec",
    "BlockRunLengthDecodeStage",
    "BlockRunLengthDecodeWindow",
    "BlockScanAlgorithm",
    "BlockScanSpec",
    "BlockShuffleMode",
    "BlockShuffleSemantics",
    "BlockShuffleSpec",
    "BlockShuffleValueKind",
    "BlockStoreAlgorithm",
    "BlockTileBoundary",
    "ScanMode",
    "ScanSemantics",
    "ScanValueKind",
    "binding",
    "make_block_adjacent_difference_semantics",
    "make_block_adjacent_difference_spec",
    "make_block_discontinuity_semantics",
    "make_block_discontinuity_spec",
    "make_block_exchange_semantics",
    "make_block_exchange_spec",
    "make_block_histogram_semantics",
    "make_block_histogram_spec",
    "make_block_load_spec",
    "make_block_load_store_semantics",
    "make_block_load_store_spec",
    "make_block_reduce_semantics",
    "make_block_reduce_spec",
    "make_block_run_length_decode_semantics",
    "make_block_run_length_decode_spec",
    "make_block_scan_spec",
    "make_block_shuffle_semantics",
    "make_block_shuffle_spec",
    "make_block_store_spec",
    "make_scan_semantics",
    "normalize_block_dim",
    "normalize_block_histogram_algorithm",
    "normalize_block_histogram_positive_int",
    "normalize_block_reduce_algorithm",
    "normalize_block_scan_algorithm",
    "normalize_boolean_option",
    "normalize_positive_int",
    "validate_block_histogram_output_capacity",
]
