blank_issues_enabled: true
contact_links:
  - name: Question
    url: https://github.com/NVIDIA/cccl/discussions
    about: Check out our Discussions page to ask and answer questions.
  - name: CUDA C++ Core Libraries Discord
    url: https://discord.gg/nvidiadeveloper
    about: Come chat about using and contributing to CCCL!
