source "https://rubygems.org"
gem "just-the-docs"
group :jekyll_plugins do
  gem "webrick"                 
  gem "github-pages"                 # GitHub Pages.
  gem "jekyll-optional-front-matter" # GitHub Pages.
  gem "jekyll-default-layout"        # GitHub Pages.
  gem "jekyll-titles-from-headings"  # GitHub Pages.
  gem "jekyll-relative-links"        # GitHub Pages.
  gem "jekyll-remote-theme"          # GitHub Pages.
end
