# Copyright (c) 2024, NVIDIA CORPORATION & AFFILIATES. ALL RIGHTS RESERVED.
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cuda-cooperative"
description = "Experimental Core Library for CUDA Python"
requires-python = ">=3.9"
dynamic = ["version", "readme"]
authors = [
    { name = "NVIDIA Corporation" }
]
license = { file = "../../LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3 :: Only",
    "Environment :: GPU :: NVIDIA CUDA",
]
dependencies = [
    "cuda-cccl @ {root:uri}/../cuda_cccl",
    "numpy",
    "numba>=0.60.0",
    "pynvjitlink-cu12>=0.2.4",
    "cuda-python",
    "jinja2",
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-xdist",
]

[project.urls]
Homepage = "https://developer.nvidia.com/"

[tool.hatch.build.targets.wheel]
packages = ["cuda"]

[tool.hatch.version]
path = "cuda/cooperative/_version.py"
attr = "__version__"

[tool.hatch.metadata]
readme = "README.md"
allow-direct-references = true
