# Copyright (c) 2024, NVIDIA CORPORATION & AFFILIATES. ALL RIGHTS RESERVED.
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cuda-cooperative"
description = "Experimental Core Library for CUDA Python"
authors = [
    { name = "NVIDIA Corporation" },
]
classifiers = [
    "Programming Language :: Python :: 3 :: Only",
    "Environment :: GPU :: NVIDIA CUDA",
    "License :: OSI Approved :: Apache Software License",
]
requires-python = ">=3.9"
dynamic = ["version", "readme", "dependencies"]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-xdist",
]

[project.urls]
Homepage = "https://developer.nvidia.com/"

[tool.setuptools.dynamic]
version = { attr = "cuda.cooperative._version.__version__" }
readme = { file = ["README.md"], content-type = "text/markdown" }
