# Copyright (c) 2024, NVIDIA CORPORATION & AFFILIATES. ALL RIGHTS RESERVED.
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

[build-system]
requires = [
    "setuptools>=61.0.0",
    "wheel",
    "packaging",
]
build-backend = "setuptools.build_meta"

[project]
name = "cuda-cooperative"
description = "Experimental Core Library for CUDA Python"
requires-python = ">=3.9"
dynamic = ["version", "readme"]
authors = [
    { name = "NVIDIA Corporation" }
]
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3 :: Only",
    "Environment :: GPU :: NVIDIA CUDA",
]
dependencies = [
    # "cuda-cccl @ file:///home/coder/cccl/python/cuda_cccl",
    "numpy",
    "numba>=0.60.0",
    "pynvjitlink-cu12>=0.2.4",
    "cuda-python",
    "jinja2",
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-xdist",
]

[project.urls]
Homepage = "https://developer.nvidia.com/"

[tool.setuptools.dynamic]
version = { attr = "cuda.cooperative._version.__version__" }
readme = { file = ["README.md"], content-type = "text/markdown" }
