# SPDX-FileCopyrightText: Copyright (c) 2024-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: Preview or clean up docs built from PRs

inputs:
  source-folder:
    description: "Path to the built documentation folder"
    required: true
    type: string
  pr-number:
    description: "PR number for the preview"
    required: true
    type: string
  github-token:
    description: "GitHub token for authentication"
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Debug deployment before action
      shell: bash
      run: |
        echo "=== Pre-deployment debugging ==="
        echo "Source folder: ${{ inputs.source-folder }}"
        echo "Target folder: docs/pr-preview/pr-${{ inputs.pr-number }}/"
        echo "Clean mode: ${{ github.ref_name == 'main' }}"
        echo "Files in source folder:"
        ls -la ${{ inputs.source-folder }}/ | head -10
        if [ -d "${{ inputs.source-folder }}/_static" ]; then
          echo "✅ _static exists in source"
          ls -la ${{ inputs.source-folder }}/_static/ | head -3
        else
          echo "❌ _static missing from source"
        fi

    - name: Deploy or clean up doc preview
      uses: JamesIves/github-pages-deploy-action@6c2d9db40f9296374acc17b90404b6e8864128c8  # v4.7.3
      with:
        github-token: ${{ inputs.github-token }}
        folder: ${{ inputs.source-folder }}
        target-folder: docs/pr-preview/pr-${{ inputs.pr-number }}/
        clean: ${{ github.ref_name == 'main' }}

    - name: Leave a comment after deployment
      if: ${{ github.ref_name != 'main' }}
      uses: marocchino/sticky-pull-request-comment@67d0dec7b07ed060a405f9b2a64b8ab319fdd7db  # v2.9.2
      with:
        header: pr-preview
        number: ${{ inputs.pr-number }}
        skip_unchanged: true
        message: |
          ## 📖 Doc Preview CI

          🚀 **Preview URL:** [https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/docs/pr-preview/pr-${{ inputs.pr-number }}/](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/docs/pr-preview/pr-${{ inputs.pr-number }}/)

          > **Note:** Preview will be ready when the GitHub Pages deployment is complete.

    - name: Leave a comment after removal
      if: ${{ github.ref_name == 'main' }}
      uses: marocchino/sticky-pull-request-comment@67d0dec7b07ed060a405f9b2a64b8ab319fdd7db  # v2.9.2
      with:
        header: pr-preview
        number: ${{ inputs.pr-number }}
        hide_and_recreate: true
        hide_classify: "OUTDATED"
        message: |
          ## 📖 Doc Preview CI

          Preview removed because the pull request was closed or merged.
