# SPDX-FileCopyrightText: Copyright (c) 2024-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: Preview or clean up docs built from PRs

inputs:
  source-folder:
    description: "Path to the built documentation folder"
    required: true
    type: string
  pr-number:
    description: "PR number for the preview"
    required: true
    type: string
  github-token:
    description: "GitHub token for authentication"
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Deploy doc preview
      if: ${{ github.ref_name != 'main' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.github-token }}
        publish_dir: ${{ inputs.source-folder }}
        destination_dir: docs/pr-preview/pr-${{ inputs.pr-number }}/
        keep_files: true

    - name: Clean up doc preview
      if: ${{ github.ref_name == 'main' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.github-token }}
        publish_dir: ${{ inputs.source-folder }}
        destination_dir: docs/pr-preview/pr-${{ inputs.pr-number }}/
        keep_files: false

    - name: Leave a comment after deployment
      if: ${{ github.ref_name != 'main' }}
      uses: marocchino/sticky-pull-request-comment@67d0dec7b07ed060a405f9b2a64b8ab319fdd7db  # v2.9.2
      with:
        header: pr-preview
        number: ${{ inputs.pr-number }}
        skip_unchanged: true
        message: |
          ## 📖 Doc Preview CI

          🚀 **Preview URL:** [https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/docs/pr-preview/pr-${{ inputs.pr-number }}/](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/docs/pr-preview/pr-${{ inputs.pr-number }}/)

          > **Note:** Preview will be ready when the GitHub Pages deployment is complete.

    - name: Leave a comment after removal
      if: ${{ github.ref_name == 'main' }}
      uses: marocchino/sticky-pull-request-comment@67d0dec7b07ed060a405f9b2a64b8ab319fdd7db  # v2.9.2
      with:
        header: pr-preview
        number: ${{ inputs.pr-number }}
        hide_and_recreate: true
        hide_classify: "OUTDATED"
        message: |
          ## 📖 Doc Preview CI

          Preview removed because the pull request was closed or merged.
