find_package(CCCL REQUIRED CONFIG
  NO_DEFAULT_PATH # Only check the explicit path in HINTS:
  HINTS "${CCCL_SOURCE_DIR}"
  COMPONENTS ${CCCL_REQUIRED_COMPONENTS}
  OPTIONAL_COMPONENTS ${CCCL_OPTIONAL_COMPONENTS}
)
