title: CUDA C++ Core Libraries

repository: nvidia/cccl

remote_theme: pmarsceill/just-the-docs

color_scheme: nvidia
logo: /images/nvidia_logo.png

search_enabled: true
search.heading_level: 4

# just-the-docs ignores these filenames by default.
include: [ "contributing.md", "code_of_conduct.md" ]

plugins_dir:
  - jekyll-remote-theme
  - jekyll-optional-front-matter # GitHub Pages.
  - jekyll-default-layout        # GitHub Pages.
  - jekyll-titles-from-headings  # GitHub Pages.
  - jekyll-relative-links        # GitHub Pages.

defaults:
  -
    scope:
      path: index.md
    values:
      title: index
      nav_order: 0
      permalink: /
