set(CudaNext_VERSION_MAJOR 2)
set(CudaNext_VERSION_MINOR 4)
set(CudaNext_VERSION_PATCH 0)
set(CudaNext_VERSION_TWEAK 0)

set(CudaNext_VERSION "${CudaNext_VERSION_MAJOR}.${CudaNext_VERSION_MINOR}.${CudaNext_VERSION_PATCH}.${CudaNext_VERSION_TWEAK}")

set(PACKAGE_VERSION ${CudaNext_VERSION})
set(PACKAGE_VERSION_COMPATIBLE FALSE)
set(PACKAGE_VERSION_EXACT FALSE)
set(PACKAGE_VERSION_UNSUITABLE FALSE)

# Semantic versioning:
if(PACKAGE_VERSION VERSION_GREATER_EQUAL PACKAGE_FIND_VERSION)
  if(CudaNext_VERSION_MAJOR VERSION_EQUAL PACKAGE_FIND_VERSION_MAJOR)
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
  endif()

  if(PACKAGE_FIND_VERSION VERSION_EQUAL PACKAGE_VERSION)
    set(PACKAGE_VERSION_EXACT TRUE)
  endif()
endif()
