# Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. ALL RIGHTS RESERVED.
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

"""Backend algorithm enums grouped by the primitives that consume them."""

from enum import IntEnum

class BlockLoadAlgorithm(IntEnum):
    DIRECT = ...
    STRIPED = ...
    VECTORIZE = ...
    TRANSPOSE = ...
    WARP_TRANSPOSE = ...
    WARP_TRANSPOSE_TIMESLICED = ...

class BlockStoreAlgorithm(IntEnum):
    DIRECT = ...
    STRIPED = ...
    VECTORIZE = ...
    TRANSPOSE = ...
    WARP_TRANSPOSE = ...
    WARP_TRANSPOSE_TIMESLICED = ...

class WarpLoadAlgorithm(IntEnum):
    DIRECT = ...
    STRIPED = ...
    VECTORIZE = ...
    TRANSPOSE = ...

class WarpStoreAlgorithm(IntEnum):
    DIRECT = ...
    STRIPED = ...
    VECTORIZE = ...
    TRANSPOSE = ...

__all__ = [
    "BlockLoadAlgorithm",
    "BlockStoreAlgorithm",
    "WarpLoadAlgorithm",
    "WarpStoreAlgorithm",
]
