name: Build and Test Python Wheels

on:
  push:

defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail {0}

jobs:
  build-cccl:
    name: Build CCCL Wheels
    uses: ./.github/workflows/run-ci-script.yml
    with:
      script-command: ci/build_cuda_cccl_python.sh -py-version ${{ matrix.python-version }}
      python-version: ${{ matrix.python-version }}
      upload-artifact: true
      upload-artifact-name: wheel-cccl-${{ matrix.python-version }}
      upload-artifact-path: ${{github.event.repository.name}}/wheelhouse/
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    permissions:
      id-token: write
      contents: read

  test-cccl:
    name: Test CCCL Wheels
    needs: build-cccl
    uses: ./.github/workflows/run-ci-script.yml
    with:
      script-command: ci/test_cuda_cccl_python.sh -py-version ${{ matrix.python-version }}
      python-version: ${{ matrix.python-version }}
      needs-artifact: true
      artifact-name: wheel-cccl-${{ matrix.python-version }}
      artifact-path: ${{github.event.repository.name}}/wheelhouse/
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    permissions:
      id-token: write
      contents: read

  build-cuda-cooperative:
    name: Build CUDA Cooperative Wheels
    uses: ./.github/workflows/run-ci-script.yml
    with:
      script-command: ci/build_cuda_cooperative_python.sh -py-version ${{ matrix.python-version }}
      python-version: ${{ matrix.python-version }}
      upload-artifact: true
      upload-artifact-name: wheel-cuda-cooperative-${{ matrix.python-version }}
      upload-artifact-path: ${{github.event.repository.name}}/wheelhouse/
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    permissions:
      id-token: write
      contents: read

  test-cuda-cooperative:
    name: Test CUDA Cooperative Wheels
    needs: build-cuda-cooperative
    uses: ./.github/workflows/run-ci-script.yml
    with:
      script-command: ci/test_cuda_cooperative_python.sh -py-version ${{ matrix.python-version }}
      python-version: ${{ matrix.python-version }}
      needs-artifact: true
      artifact-name: wheel-cuda-cooperative-${{ matrix.python-version }}
      artifact-path: ${{github.event.repository.name}}/wheelhouse/
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    permissions:
      id-token: write
      contents: read

  build-cuda-parallel:
    name: Build CUDA Parallel Wheels
    uses: ./.github/workflows/run-ci-script.yml
    with:
      script-command: ci/build_cuda_parallel_python.sh -py-version ${{ matrix.python-version }}
      python-version: ${{ matrix.python-version }}
      upload-artifact: true
      upload-artifact-name: wheel-cuda-parallel-${{ matrix.python-version }}
      upload-artifact-path: ${{github.event.repository.name}}/wheelhouse/
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    permissions:
      id-token: write
      contents: read

  test-cuda-parallel:
    name: Test CUDA Parallel Wheels
    needs: build-cuda-parallel
    uses: ./.github/workflows/run-ci-script.yml
    with:
      script-command: ci/test_cuda_parallel_python.sh -py-version ${{ matrix.python-version }}
      python-version: ${{ matrix.python-version }}
      needs-artifact: true
      artifact-name: wheel-cuda-parallel-${{ matrix.python-version }}
      artifact-path: ${{github.event.repository.name}}/wheelhouse/
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    permissions:
      id-token: write
      contents: read
