# SPDX-FileCopyrightText: Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: Source PR

on:
  push:
    branches:
      - "pull-request/[0-9]+"

jobs:
  ci:
    name: Run pull request CI
    permissions:
      actions: read
      checks: read
      contents: read
      id-token: write
      packages: read
      pull-requests: write
    uses: NVIDIA/cccl/.github/workflows/ci-workflow-pull-request.yml@ci
    secrets: inherit
    with:
      source_ref: ${{ github.sha }}
