# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: Source Nightly

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1-5"

jobs:
  ci:
    name: Run nightly CI
    permissions:
      actions: read
      checks: read
      contents: read
      id-token: write
      packages: read
      pull-requests: read
    uses: NVIDIA/cccl/.github/workflows/ci-workflow-nightly.yml@ci
    secrets: inherit
    with:
      source_ref: ${{ github.sha }}
