# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: Source Weekly

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 0"

jobs:
  ci:
    name: Run weekly CI
    permissions:
      actions: read
      checks: read
      contents: read
      id-token: write
    uses: NVIDIA/cccl/.github/workflows/ci-workflow-weekly.yml@ci
    secrets: inherit
    with:
      source_ref: ${{ github.sha }}
