
name: Compute the matrix for a given matrix type from the specified matrix file

on:
  workflow_call:
    inputs:
      matrix_file: 
        type: string
        required: true
      matrix_type:
        description: "The desired matrix type. Currently, only 'pull-request' and 'nightly' are supported."
        type: string
        required: true
    outputs:
      FULL_MATRIX: 
        description: "The full matrix of build configurations for the given matrix type."
        value: ${{ jobs.compute-matrix.outputs.FULL_MATRIX }}
      CUDA_VERSIONS:
        description: "The unique CUDA versions in the full matrix."
        value: ${{ jobs.compute-matrix.outputs.CUDA_VERSIONS }}
      COMPILERS:
        description: "The unique compilers in the full matrix."
        value: ${{ jobs.compute-matrix.outputs.COMPILERS }}
      PER_CUDA_COMPILER_MATRIX:
        description: "The matrix of build configurations for each CUDA version and compiler."
        value: ${{ jobs.compute-matrix.outputs.PER_CUDA_COMPILER_MATRIX }}

defaults:
  run:
    shell: bash

env:
  MATRIX_TYPE: ${{ inputs.matrix_type}}
  MATRIX_FILE: ${{ inputs.matrix_file }}

jobs:
  compute-matrix:
    name: ${{inputs.matrix_type}} 
    runs-on: ubuntu-latest
    outputs:
      FULL_MATRIX:  ${{ steps.compute-matrix.outputs.FULL_MATRIX }}
      CUDA_VERSIONS: ${{ steps.compute-matrix.outputs.CUDA_VERSIONS }}
      COMPILERS: ${{ steps.compute-matrix.outputs.COMPILERS }}
      PER_CUDA_COMPILER_MATRIX: ${{ steps.compute-matrix.outputs.PER_CUDA_COMPILER_MATRIX }}
    steps:
      - name: Validate matrix type
        run: |
          if [[ "$MATRIX_TYPE" != "pull-request" && "$MATRIX_TYPE" != "nightly" ]]; then
            echo "Invalid build type: $MATRIX_TYPE. Must be 'nightly' or 'pull-request'"
            exit 1
          fi
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Compute matrix
        id: compute-matrix
        run: |
          pwd
          ls -la
          MATRIX_FILE=$(realpath "${MATRIX_FILE}")
          ./.github/workflows/compute-matrix.sh "$MATRIX_FILE" '.["'"$MATRIX_TYPE"'"]["nvcc"]'