name: Build PR Documentation Preview

on:
  workflow_call:
    inputs:
      pr_number:
        description: "PR number for preview deployment"
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write
  pages: write

# Serialize all gh-pages deployments
concurrency:
  group: gh-pages-deploy
  cancel-in-progress: false

jobs:
  build-and-deploy:
    name: Build and deploy PR preview
    runs-on: linux-amd64-cpu32
    steps:
      - name: Validate PR number
        run: |
          if ! echo "${{ inputs.pr_number }}" | grep -qE '^[0-9]+$'; then
            echo "Error: pr_number must be numeric (got: '${{ inputs.pr_number }}')"
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Build documentation
        uses: ./.github/actions/docs-build
        with:
          target_dir: "_pr_preview"

      - name: Deploy PR preview
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_pr_preview
          publish_branch: gh-pages
          destination_dir: docs/pr-preview/pr-${{ inputs.pr_number }}
          keep_files: true
          commit_message: "Deploy doc preview for PR ${{ inputs.pr_number }} (${{ github.sha }})"

      - name: Comment on PR
        uses: marocchino/sticky-pull-request-comment@67d0dec7b07ed060a405f9b2a64b8ab319fdd7db  # v2.9.2
        with:
          header: pr-preview
          number: ${{ inputs.pr_number }}
          skip_unchanged: true
          message: |
            ## 📖 Doc Preview CI

            | :rocket: **View preview at** |
            |:---:|
            | https://nvidia.github.io/cccl/pr-preview/pr-${{ inputs.pr_number }}/ |

            <h6>Preview will be ready when the GitHub Pages deployment is complete.</h6>
