name: Source Git Bisect

on:
  workflow_dispatch:
    inputs:
      runner:
        description: "Runner label. Ex: 'linux-amd64-cpu16', 'linux-amd64-gpu-rtxa6000-latest-1'"
        required: true
        default: "linux-amd64-cpu16"
        type: string
      launch_args:
        description: "Devcontainer launch args. Ex: '--cuda 13.3 --host gcc14'"
        required: false
        default: "--cuda 13.3 --host gcc14"
        type: string
      preset:
        description: "CMake preset. Ex: cub-cpp20"
        required: true
        default: "cub-cpp20"
        type: string
      cmake_options:
        description: "Additional options passed to CMake preset configure."
        required: false
        default: ""
        type: string
      build_targets:
        description: "Space-separated Ninja build targets."
        required: false
        default: ""
        type: string
      ctest_targets:
        description: "Space-separated CTest -R regular expressions."
        required: false
        default: ""
        type: string
      lit_precompile_tests:
        description: "Space-separated libcudacxx lit tests to compile without execution."
        required: false
        default: ""
        type: string
      lit_tests:
        description: "Space-separated libcudacxx lit tests to compile and execute."
        required: false
        default: ""
        type: string
      good_ref:
        description: "Good ref/SHA/tag/branch. '-Nd' means N days ago on main."
        required: false
        type: string
      bad_ref:
        description: "Bad ref/SHA/tag/branch. '-Nd' means N days ago on main."
        required: false
        type: string

jobs:
  ci:
    name: Run Git bisect
    permissions:
      contents: read
      id-token: write
    uses: NVIDIA/cccl/.github/workflows/git-bisect.yml@ci
    secrets: inherit
    with:
      source_ref: ${{ github.sha }}
      runner: ${{ inputs.runner }}
      launch_args: ${{ inputs.launch_args }}
      preset: ${{ inputs.preset }}
      cmake_options: ${{ inputs.cmake_options }}
      build_targets: ${{ inputs.build_targets }}
      ctest_targets: ${{ inputs.ctest_targets }}
      lit_precompile_tests: ${{ inputs.lit_precompile_tests }}
      lit_tests: ${{ inputs.lit_tests }}
      good_ref: ${{ inputs.good_ref }}
      bad_ref: ${{ inputs.bad_ref }}
