# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Deploy PR Documentation Preview

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

concurrency:
  group: docs-preview-${{ github.ref }}
  cancel-in-progress: true

# Permissions needed for GitHub Pages deployment and PR comments
permissions:
  contents: read
  pages: write
  pull-requests: write
  id-token: write

jobs:
  build-and-deploy-preview:
    name: Build and Deploy Documentation Preview
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Build documentation
        uses: ./.github/actions/docs-build
        with:
          upload_workflow_artifact: "false"
          upload_pages_artifact: "false"

      - name: Deploy documentation preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: _site/
          preview-url: https://nvidia.github.io/cccl/
          umbrella-dir: pr-preview
          action: deploy

  cleanup-preview:
    name: Cleanup Documentation Preview
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    steps:
      - name: Remove documentation preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: _site/
          preview-url: https://nvidia.github.io/cccl/
          umbrella-dir: pr-preview
          action: remove
