name: Clean up PR preview docs

on:
  pull_request_target:
    types: [closed]

concurrency:
  group: pr-preview-${{ github.event.pull_request.number }}
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write
  pages: write

jobs:
  cleanup-preview:
    name: Clean up documentation preview
    uses: ./.github/workflows/build-docs.yml
    with:
      destination_dir: docs/pr-preview/pr-${{ github.event.pull_request.number }}
      pr_number: ${{ github.event.pull_request.number }}
      remove_pr_preview: true
