name: Clean up PR preview docs

on:
  pull_request:
    types: [closed]

# Prevent multiple cleanup runs for the same PR from interfering
concurrency:
  group: pr-preview-cleanup-${{ github.event.pull_request.number }}
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write

jobs:
  cleanup-preview:
    name: Clean up documentation preview
    # Clean up previews for any closed PR (merged or not)
    # If a PR is closed, the preview is no longer relevant
    uses: ./.github/workflows/build-docs.yml
    with:
      destination_dir: docs/pr-preview/pr-${{ github.event.pull_request.number }}
      pr_number: ${{ github.event.pull_request.number }}
      remove_pr_preview: true
