# NVHPC compiler file for CUDA language. Must be placed in "Compiler/" directory.
#
# Warning: This is an internal-only feature used for cub testing for stdpar. It is generated by codex and may contain
#          nonsense.

include(Compiler/NVHPC)
__compiler_nvhpc(CUDA)

set(CMAKE_CUDA_COMPILER_HAS_DEVICE_LINK_PHASE FALSE)
set(_CMAKE_COMPILE_AS_CUDA_FLAG "-x cu")

function(__compiler_nvhpc_cuda_architectures_to_flags out_var architectures)
  set(_flags "")

  if ("${architectures}" STREQUAL "" OR "${architectures}" STREQUAL "OFF")
    set(${out_var} "${_flags}" PARENT_SCOPE)
    return()
  elseif ("${architectures}" STREQUAL "all")
    set(${out_var} "-gpu=ccall" PARENT_SCOPE)
    return()
  elseif ("${architectures}" STREQUAL "all-major")
    set(${out_var} "-gpu=ccall-major" PARENT_SCOPE)
    return()
  elseif ("${architectures}" STREQUAL "native")
    set(${out_var} "-gpu=ccnative" PARENT_SCOPE)
    return()
  endif()

  foreach (_arch IN LISTS architectures)
    string(REGEX REPLACE "-(real|virtual)$" "" _arch "${_arch}")
    if (_arch MATCHES "^([0-9]+)[af]$")
      message(
        WARNING
        "NVHPC does not support CUDA architecture suffix '${_arch}'. Using '${CMAKE_MATCH_1}' instead."
      )
      set(_arch "${CMAKE_MATCH_1}")
    endif()

    if (_arch MATCHES "^[0-9]+$")
      list(APPEND _gpu_architectures "cc${_arch}")
    else()
      message(
        WARNING
        "Ignoring unsupported NVHPC CUDA architecture '${_arch}'."
      )
    endif()
  endforeach()

  if (_gpu_architectures)
    list(REMOVE_DUPLICATES _gpu_architectures)
    string(REPLACE ";" "," _gpu_architectures "${_gpu_architectures}")
    set(_flags "-gpu=${_gpu_architectures}")
  endif()

  set(${out_var} "${_flags}" PARENT_SCOPE)
endfunction()

set(CMAKE_DEPFILE_FLAGS_CUDA "-MD -MT <DEP_TARGET> -MF <DEP_FILE>")
set(CMAKE_CUDA_DEPFILE_FORMAT gcc)
set(CMAKE_CUDA_DEPENDS_USE_COMPILER TRUE)

# CMake appends _CMAKE_CUDA_WHOLE_FLAG to every CUDA object compilation and
# prepends _CMAKE_CUDA_RDC_FLAG when CUDA_SEPARABLE_COMPILATION is enabled.
# Keep nordc in the ordinary flags so an explicit rdc request can override it.
set(_CMAKE_CUDA_WHOLE_FLAG "-c -gpu=nordc")
set(_CMAKE_CUDA_RDC_FLAG "-gpu=rdc")

set(CMAKE_CUDA_DEVICE_LINK_MODE DRIVER)
set(CMAKE_CUDA_COMPILER_ABI "ELF")

set(CMAKE_CUDA_COMPILE_OPTIONS_PIC "-fPIC")
set(CMAKE_CUDA_COMPILE_OPTIONS_PIE "-fPIE")
set(CMAKE_CUDA_LINK_OPTIONS_PIE "-fPIE")
set(CMAKE_CUDA_LINK_OPTIONS_NO_PIE "-fno-pie")
set(CMAKE_SHARED_LIBRARY_CUDA_FLAGS "-fPIC")
set(CMAKE_SHARED_LIBRARY_CREATE_CUDA_FLAGS "-shared")
set(CMAKE_SHARED_LIBRARY_LINK_CUDA_FLAGS "")

set(
  CMAKE_CUDA_LINK_EXECUTABLE
  "<CMAKE_CUDA_COMPILER> <FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>${__IMPLICIT_LINKS}"
)
set(
  CMAKE_CUDA_CREATE_SHARED_LIBRARY
  "<CMAKE_CUDA_COMPILER> <CMAKE_SHARED_LIBRARY_CUDA_FLAGS> <LANGUAGE_COMPILE_FLAGS> <LINK_FLAGS> <SONAME_FLAG><TARGET_SONAME> -o <TARGET> <OBJECTS> <LINK_LIBRARIES>${__IMPLICIT_LINKS}"
)
set(CMAKE_CUDA_CREATE_SHARED_MODULE "${CMAKE_CUDA_CREATE_SHARED_LIBRARY}")

# Mixed CXX/CUDA targets may link with the CXX rule. Teach CMake that CUDA
# runtime selection for NVHPC is the driver-level -cuda option rather than a
# hand-written cudart library list.
set(CMAKE_CUDA_RUNTIME_LIBRARY_DEFAULT "SHARED")
set(CMAKE_CUDA_RUNTIME_LIBRARY_LINK_OPTIONS_STATIC "-cuda")
set(CMAKE_CUDA_RUNTIME_LIBRARY_LINK_OPTIONS_SHARED "-cuda")
set(CMAKE_CUDA_RUNTIME_LIBRARY_LINK_OPTIONS_NONE "")

set(CMAKE_CUDA03_STANDARD_COMPILE_OPTION --c++03)
set(CMAKE_CUDA03_EXTENSION_COMPILE_OPTION --c++03 --gnu_extensions)
set(CMAKE_CUDA03_STANDARD__HAS_FULL_SUPPORT ON)
set(CMAKE_CUDA11_STANDARD_COMPILE_OPTION --c++11)
set(CMAKE_CUDA11_EXTENSION_COMPILE_OPTION --c++11 --gnu_extensions)
set(CMAKE_CUDA11_STANDARD__HAS_FULL_SUPPORT ON)
set(CMAKE_CUDA14_STANDARD_COMPILE_OPTION --c++14)
set(CMAKE_CUDA14_EXTENSION_COMPILE_OPTION --c++14 --gnu_extensions)
set(CMAKE_CUDA14_STANDARD__HAS_FULL_SUPPORT ON)
set(CMAKE_CUDA17_STANDARD_COMPILE_OPTION --c++17)
set(CMAKE_CUDA17_EXTENSION_COMPILE_OPTION --c++17 --gnu_extensions)
set(CMAKE_CUDA20_STANDARD_COMPILE_OPTION --c++20)
set(CMAKE_CUDA20_EXTENSION_COMPILE_OPTION --c++20 --gnu_extensions)
set(CMAKE_CUDA23_STANDARD_COMPILE_OPTION --c++23)
set(CMAKE_CUDA23_EXTENSION_COMPILE_OPTION --c++23 --gnu_extensions)
set(CMAKE_CUDA_STANDARD_LATEST 23)

set(CMAKE_CUDA_STANDARD_DEFAULT "${CMAKE_CXX_STANDARD_DEFAULT}")
set(CMAKE_CUDA_EXTENSIONS_DEFAULT "${CMAKE_CXX_EXTENSIONS_DEFAULT}")

set(CMAKE_CUDA03_COMPILE_FEATURES cuda_std_03)
set(CMAKE_CUDA11_COMPILE_FEATURES cuda_std_11)
set(CMAKE_CUDA14_COMPILE_FEATURES cuda_std_14)
set(CMAKE_CUDA17_COMPILE_FEATURES cuda_std_17)
set(CMAKE_CUDA20_COMPILE_FEATURES cuda_std_20)
set(CMAKE_CUDA23_COMPILE_FEATURES cuda_std_23)
set(
  CMAKE_CUDA_COMPILE_FEATURES
  cuda_std_03
  cuda_std_11
  cuda_std_14
  cuda_std_17
  cuda_std_20
  cuda_std_23
)

__compiler_nvhpc_cuda_architectures_to_flags(
  _CMAKE_CUDA_ARCHITECTURE_FLAGS
  "${CMAKE_CUDA_ARCHITECTURES}"
)

if (_CMAKE_CUDA_ARCHITECTURE_FLAGS)
  string(APPEND CMAKE_CUDA_FLAGS_INIT " ${_CMAKE_CUDA_ARCHITECTURE_FLAGS}")
endif()

string(
  APPEND CMAKE_CUDA_FLAGS_INIT
  " -cuda --diag_suppress cuda_compile --diag_suppress no_device_stack"
)
